<?php

namespace Ebay\Sell\Metadata\Model;

use OpenAPI\Runtime\AbstractModel;

class AutomotivePartsCompatibilityPolicyResponse extends AbstractModel
{
    /**
     * A list of category IDs and the automotive-parts-compatibility policies for each
     * of the listed categories.
     *
     * @var \Ebay\Sell\Metadata\Model\AutomotivePartsCompatibilityPolicy[]
     */
    public $automotivePartsCompatibilityPolicies = null;

    /**
     * A list of the warnings that were generated as a result of the request. This
     * field is not returned if no warnings were generated by the request.
     *
     * @var \Ebay\Sell\Metadata\Model\Error[]
     */
    public $warnings = null;
}
