<?php

namespace Ebay\Sell\Metadata\Model;

use OpenAPI\Runtime\AbstractModel;

class ListingStructurePolicyResponse extends AbstractModel
{
    /**
     * Returns a list of category IDs plus a flag indicating whether or not each listed
     * category supports item variations.
     *
     * @var \Ebay\Sell\Metadata\Model\ListingStructurePolicy[]
     */
    public $listingStructurePolicies = null;

    /**
     * A list of the warnings that were generated as a result of the request. This
     * field is not returned if no warnings were generated by the request.
     *
     * @var \Ebay\Sell\Metadata\Model\Error[]
     */
    public $warnings = null;
}
