<?php

namespace Ebay\Sell\Metadata\Model;

use OpenAPI\Runtime\AbstractModel;

class ReturnPolicyResponse extends AbstractModel
{
    /**
     * A list of elements, where each contains a category ID and a flag that indicates
     * whether or not listings in that category require a return policy.
     *
     * @var \Ebay\Sell\Metadata\Model\ReturnPolicy[]
     */
    public $returnPolicies = null;

    /**
     * A list of the warnings that were generated as a result of the request. This
     * field is not returned if no warnings were generated by the request.
     *
     * @var \Ebay\Sell\Metadata\Model\Error[]
     */
    public $warnings = null;
}
